name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    # Step 4: Train model & log MLflow results (if model training runs in CI)
    - name: Run training script
      run: python src/train.py  # Make sure your script logs to mlruns/

    # Step 5: Upload MLflow logs as an artifact
    - name: Upload MLflow logs
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-logs
        path: mlruns/


    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t mshisheh/linear-sklearn .

    # Push the Docker image
    - name: Push the Docker image
      run: docker push mshisheh/linear-sklearn:latest


    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@v0.1.9
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ubuntu  # Or ec2-user if using Amazon Linux
    #     key: ${{ secrets.DEPLOY_KEY }}
    #     script: |
    #       docker pull mshisheh/linear-sklearn
    #       docker stop linear-sklearn || true
    #       docker rm linear-sklearn || true
    #       docker run -d --name linear-sklearn -p 80:80 mshisheh/linear-sklearn:latest