name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t mshisheh/linear-sklearn .

    # Push the Docker image
    - name: Push the Docker image
      run: docker push mshisheh/linear-sklearn:latest


    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@v0.1.9
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ubuntu  # Or ec2-user if using Amazon Linux
    #     key: ${{ secrets.DEPLOY_KEY }}
    #     script: |
    #       docker pull mshisheh/linear-sklearn
    #       docker stop linear-sklearn || true
    #       docker rm linear-sklearn || true
    #       docker run -d --name linear-sklearn -p 80:80 mshisheh/linear-sklearn:latest